In [2]:
# Шаг 6_4_1

# Numpy-100 (задачи 11-20)

# Урок создан на основании известного сборника задач Numpy-100 - https://github.com/rougier/numpy-100

# Постарайтесь не подглядывать в ответы. =)


In [16]:
# Шаг 6_4_2

# 11

# Считайте число n

# Создайте единичную матрицу размера n, сохраните результат в переменную Z.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

import numpy as np

n = int(input())

Z = np.eye(n, dtype = float)

# print(Z)

# Дока: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.eye.html

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
