In [ ]:
# Шаг 7_2_1

# Спектральное и сингулярное разложение матриц

# 1. Спектральное разложение матриц
# 2. Что такое квадратичные формы
# 3. Упрощение квадратичных форм с помощью спектрального разложения
# 4. Сингулярное разложение матриц
# 5. Связь между спектральным и сингулярным разложениями (частный случай для квадратных матриц)

In [1]:
# Шаг 7_2_2

# Спектральное разложение матрицы

import numpy as np

np.set_printoptions(precision = 2, suppress = True)

A = np.array([[1.0, 2.0, -1.0], [2.0, 2.0, 5.0], [-1.0, 5.0, -3.0]])
A

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])

In [3]:
v, w = np.linalg.eigh(A)

In [4]:
v

array([-6.5753629 ,  1.14911837,  5.42624453])

In [5]:
w

array([[-0.24709   ,  0.92927297, -0.27458749],
       [ 0.5304425 , -0.10742791, -0.84088643],
       [-0.81091139, -0.3534275 , -0.46638151]])

In [7]:
D = np.diag(v)
D

array([[-6.5753629 ,  0.        ,  0.        ],
       [ 0.        ,  1.14911837,  0.        ],
       [ 0.        ,  0.        ,  5.42624453]])

In [8]:
S = w.T
S

array([[-0.24709   ,  0.5304425 , -0.81091139],
       [ 0.92927297, -0.10742791, -0.3534275 ],
       [-0.27458749, -0.84088643, -0.46638151]])

In [9]:
S.T

array([[-0.24709   ,  0.92927297, -0.27458749],
       [ 0.5304425 , -0.10742791, -0.84088643],
       [-0.81091139, -0.3534275 , -0.46638151]])

In [11]:
np.dot(S.T, S)

array([[1.00000000e+00, 5.80413027e-17, 1.16447902e-16],
       [5.80413027e-17, 1.00000000e+00, 4.58528324e-17],
       [1.16447902e-16, 4.58528324e-17, 1.00000000e+00]])

In [12]:
np.dot(np.dot(S.T, D), S)

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])

In [13]:
# Шаг 7_2_3

# Квадратичные формы

# P(x,y,z) = x**2 + 2*y**2 - 3*z**2 + 4*x*y + 10*y*z - 2*x*z

#                   (1  2 -1  (x
# P(x,y,z) = (x y z) 2  2  5   y
#                   -1  5 -3 ) z)


In [14]:
# Шаг 7_2_4

# Выберите все функции, являющиеся квадратичными формами

# Выберите все подходящие ответы из списка:

# - P(x) = 8x³ - 4x² + 2x - 1
# - P(x, y) = x⁴ + y³ + x² + y + 42
# - P(x) = 9x² - 6x + 1
# + P(x) = x²
# + P(x, y) = x² + 2xy + y²
# + P(x, y) = (3x - 2y)²
# - P(x) = (3x - 1)²
# - P(x, y) = x² + 2xy + y² + 3x + 3y + 4



In [15]:
# Шаг 7_2_5

# Выберите все функции, являющиеся квадратичными формами

# В данном вопросе есть небольшой подвох.

# Выберите все подходящие ответы из списка:

# - P(x, y) = (x + y)²
# - P(x, y) = x²
# - P(x, y) = x² + y²
# - P(x, y) = x² + xy + y²
# - P(x, y) = xy
