In [2]:
# Шаг 6_2_1

# Темы семинара 3

# Математика:
#   - Введение - Линейная независимость векторов, ранг матрицы, ранг по строкам и столбцам.
#   - Задача 1 - Линейная независимость 3 векторов
#   - Задача 2 - Максимальное число линейно независимых векторов из набора 6
#   - Задача 3 - Какие из векторов образуют базис
#   - Норма и метрика. Что это и зачем нужно?
#   - Косинусное расстояние и близость


In [ ]:
# Шаг 6_2_2

Линейная независимость векторов

In [1]:
import numpy as np

e1 = np.array([1., 0., 0.])
e2 = np.array([0., 5., 0.])


In [6]:
-3*e1 + 2*e2

array([-3., 10.,  0.])

In [8]:
0*e1 + 0*e2 # не интересует, тривиальная комбинация

array([0., 0., 0.])

In [5]:
a = np.array([-3., 10., 0.])


In [7]:
3*e1 - 2*e2 + 1*a

array([0., 0., 0.])

In [11]:
a == -3*e1 + 2*e2


array([ True,  True,  True])

Линейная независимость векторов и ранг матрицы

In [13]:
M = np.array([e1, e2, a])
M

array([[ 1.,  0.,  0.],
       [ 0.,  5.,  0.],
       [-3., 10.,  0.]])

In [16]:
np.linalg.matrix_rank(M)

np.int64(2)

Ранг матрицы по строкам и столбцам

In [17]:
b1, b2, b3 = M[:, 0], M[:, 1], M[:, 2]

In [19]:
b1

array([ 1.,  0., -3.])

In [21]:
0*b1 + 0*b2 + 1*b3

array([0., 0., 0.])

В матрице число линейно независимых строк равно числу линейно независимых столбцов

Линейная независимость векторов

In [ ]:
# Шаг 6_2_3

# 1. Рассмотрим 3 вектора:
#   [a]   [b]   [c]
#   [0] , [d] , [e]
#   [0]   [0]   [f]

# Известно, что три числа из набора чисел {a, b, c, d, e, f} равны нулю, а оставшиеся три — отличны от нуля.

# Выберите варианты, при которых эти векторы линейно зависимы.
#
# 1. a=0, b=0, f=0
# 2. b=0, e=0, f=0
# 3. c=0, d=0, f=0
# 4. b=0, c=0, e=0
# 5. a=0, b=0, d=0
# 6. a=0, e=0, f=0

In [26]:
import numpy as np

M = np.array([
    #a, b, c, d, e, f
    [0, 0, 1, 1, 1, 0],
    [1, 0, 1, 1, 0, 0],
    [1, 1, 0, 0, 1, 0],
    [1, 0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1, 1],
    [0, 1, 1, 0, 0, 0]
])
M

array([[0, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0, 0]])

In [29]:
for a,b,c,d,e,f in M:
    N = np.array([
        [a,0,0],
        [b,d,0],
        [c,e,f]
    ])
    print(N)
    print(np.linalg.matrix_rank(N))
    print(a,b,c,d,e,f)

[[0 0 0]
 [0 1 0]
 [1 1 0]]
2
0 0 1 1 1 0
[[1 0 0]
 [0 1 0]
 [1 0 0]]
2
1 0 1 1 0 0
[[1 0 0]
 [1 0 0]
 [0 1 0]]
2
1 1 0 0 1 0
[[1 0 0]
 [0 1 0]
 [0 0 1]]
3
1 0 0 1 0 1
[[0 0 0]
 [0 0 0]
 [1 1 1]]
1
0 0 1 0 1 1
[[0 0 0]
 [1 0 0]
 [1 0 0]]
1
0 1 1 0 0 0


In [ ]:
# только в четвёртом варианте получилось три (ранг матрицы), поэтому только в варианте 4 вектора линейно независимы, в остальных - зависимы

Число независимых векторов из набора

In [30]:
# Шаг 6_2_4

# 2. Найдите среди заданных шести векторов вида
#   [1]   [1]   [1]   [0]   [0]   [0]
#   [-1], [0], [0], [1], [1], [0]
#   [0]   [-1]  [0]   [-1]  [0]   [1]
#   [0]   [0]   [-1]  [0]   [-1]  [-1]

# наибольшее количество линейно независимых векторов.

In [32]:

import numpy as np

M = np.array([
    [1, -1, 0, 0],
    [1, 0, -1, 0],
    [1, 0, 0, -1],
    [0, 1, -1, 0],
    [0, 1, 0, -1],
    [0, 0, 1, -1]
])
M

array([[ 1, -1,  0,  0],
       [ 1,  0, -1,  0],
       [ 1,  0,  0, -1],
       [ 0,  1, -1,  0],
       [ 0,  1,  0, -1],
       [ 0,  0,  1, -1]])

In [33]:
np.linalg.matrix_rank(M)

np.int64(3)

In [ ]:
# Шаг 6_2_5

Какие из векторов образуют базис

In [ ]:
# 3. Какие из нижеперечисленных векторов образуют базис в трёхмерном пространстве ℝ³?

# Hint. Базис образуют линейно независимые вектора, из линейной комбинации которых можно получить любой вектор в пространстве данной размерности.

# 1. (1, 2, 0), (0, 1, -1)
# 2. (1, 1, -1), (2, 3, 4), (4, 1, -1), (0, 1, -1)
# 3. (1, 2, 2), (-1, 2, 1), (0, 8, 0)
# 4. (1, 2, 2), (-1, 2, 1), (0, 8, 6)

In [45]:
import numpy as np

# нужно число векторов совпадающих с размерностью пространства, поэтому 2 и 4 вектора не смогут образовать базис

MM = np.array([
    [
        (1, 2, 2),
        (-1, 2, 1),
        (0, 8, 0),
    ],
    [
        (1, 2, 2),
        (-1, 2, 1),
        (0, 8, 6),
    ]
])

MM[0]

array([[ 1,  2,  2],
       [-1,  2,  1],
       [ 0,  8,  0]])

In [46]:
for M in MM:
    print(M)
    print(np.linalg.matrix_rank(M))
    # ранг матрицы должен совпадать с числом векторов, тогда эти вектора образуют базис (в данном случае в трёхмерном пространстве)

[[ 1  2  2]
 [-1  2  1]
 [ 0  8  0]]
3
[[ 1  2  2]
 [-1  2  1]
 [ 0  8  6]]
2


In [47]:
# Ответ: #3  (1, 2, 2), (-1, 2, 1), (0, 8, 0)