In [2]:
# Шаг 6_4_1

# Numpy-100 (задачи 11-20)

# Урок создан на основании известного сборника задач Numpy-100 - https://github.com/rougier/numpy-100

# Постарайтесь не подглядывать в ответы. =)


In [16]:
# Шаг 6_4_2

# 11

# Считайте число n

# Создайте единичную матрицу размера n, сохраните результат в переменную Z.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

import numpy as np
from sympy.stats.sampling.sample_numpy import numpy

n = int(input())

Z = np.eye(n, dtype = float)

# print(Z)

# Дока: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.eye.html

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# Шаг 6_4_3

# 12

# Считайте 3 числа: n, m, l.

# Зафиксируйте значение генератора случайных чисел Numpy с помощью:
#   numpy.random.seed(42)

# Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и сохраните результат в переменную Z.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

import numpy as np

np.random.seed(42)

n, m, l = list(map(int, input().split()))

# Дока: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html

Z = np.random.random_sample((n,m,l))

print(Z)


[[[0.37454012 0.95071431]
  [0.73199394 0.59865848]]

 [[0.15601864 0.15599452]
  [0.05808361 0.86617615]]]


In [ ]:
# Шаг 6_4_4

# Лирическое отступление - ГПСЧ

# Генератор псевдослучайных чисел (ГПСЧ) — важнейшая часть многих программ.
# И не только онлайн казино или алгоритмов моделирования, но так же алгоритмов шифрования, анализа данных и т.п.

# Важно понимать, источников по настоящему случайных чисел мало.
# Кроме того, в работе они не всегда удобны.
# Именно поэтому в работе мы и используем "псевдослучайные" числа.
# Зная алгоритм генерации и начальное значение, всегда можно предсказать следующее.

# Именно этим мы пользуемся, когда фиксируем seed:
#   numpy.random.seed(42)

# Если бы это сделать было нельзя, то нам бы не удалось проверить ваше предыдущее задание
# (только если поверить на слово, что список из одних 1 единиц получился совершенно случайно, правда-правда).

# Во многих задачах специализации вам необходимо фиксировать seed,
# например, при перемешивании элементов для формирования обучающей и контрольной выборки (но не будем забегать вперёд).
# Поэтому всегда внимательно читайте

In [6]:
# Шаг 6_4_5

# 13

# Считайте 2 числа: n, m.

# Зафиксируйте значение генератора случайных чисел Numpy с помощью:
#   numpy.random.seed(42)

# Создайте матрицу n*m из случайных чисел (от 0 до 1).

# Выведите на печать значение минимального и максимального чисел в получившейся матрице (каждое с новой строки).

import numpy as np

np.random.seed(42)

n, m = list(map(int, input().split()))

Z = np.random.random_sample((n,m))

# print(Z)

print(np.min(Z))
print(np.max(Z))


0.005522117123602399
0.9868869366005173


In [12]:
# Шаг 6_4_6

# 14

# Считайте 2 числа: n, m.

# Зафиксируйте значение генератора случайных чисел Numpy с помощью:
#   numpy.random.seed(42)

# Создайте матрицу n*m из случайных чисел (от 0 до 1).

# Выведите на печать значение среднего для всей матрицы.

import numpy as np

np.random.seed(42)

n,m = list(map(int, input().split()))

Z = np.random.random_sample((n,m))

print(np.mean(Z))
# print(np.average(Z))

# print(Z)

0.47018074337820936


In [17]:
# Шаг 6_4_7

# Считайте 2 числа: n, m.

# Зафиксируйте значение генератора случайных чисел Numpy с помощью:
#   numpy.random.seed(42)

# Создайте матрицу n*m из случайных чисел (от 0 до 1).

# Найдите среднее значение для каждого из столбцов.

# Выведите на печать значение минимального и максимального среднего по столбцам (каждое с новой строки).

# Дока: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.mean.html?highlight=mean#numpy.mean

import numpy as np

np.random.seed(42)

n,m = list(map(int, input().split()))

Z = np.random.random_sample((n,m))

print(np.min(np.mean(Z, axis = 0)))
print(np.max(np.mean(Z, axis = 0)))

# print(Z)

0.270220682758469
0.8115814940446553


In [36]:
# Шаг 6_4_8

# 15

# Считайте 2 числа: n, m.

# Создайте матрицу размера n*m такую что:
#   - На границе матрицы будут стоять 1
#   - Внутри матрицы будут стоять 0

# Сохраните матрицу в переменную Z.

# Гарантируется, что матрица будет не меньше 3x3.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

import numpy as np

n, m = list(map(int, input().split()))

Z = np.zeros((n,m))

Z[0] = 1.0
Z[-1] = 1.0
Z[:, 0] = 1.0
Z[:, -1] = 1.0

print(Z)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [37]:
import numpy as np

n,m = list(map(int, input().split()))

Z = np.ones((n,m))

Z[1:-1, 1:-1] = 0.

print(Z)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [86]:
# Шаг 6_4_9

import numpy as np


Z = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# функцию взял из доки: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.pad.html

def pad_with(vector, pad_width, iaxis, kwargs):
        pad_value = kwargs.get('padder', 10)
        vector[:pad_width[0]] = pad_value
        vector[-pad_width[1]:] = pad_value
        return vector



Z = np.pad(Z, 1, pad_with, padder = 0.)

print(Z)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [98]:
# Проще и нагляднее так:

import numpy as np


Z = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Z =  np.pad(Z, ((1,1),(1,1)), mode = 'constant', constant_values = 0)

print(Z)


[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [7]:
# Шаг 6_4_10

import numpy

print(0.3 == 3 * 0.1)
print(numpy.nan - numpy.nan)
print(numpy.nan == numpy.nan)
print(numpy.inf > numpy.nan)
print(numpy.nan in set([numpy.nan]))
print(numpy.isnan(numpy.nan))
print(0 * numpy.nan)

'''
Выражение
Результат
Объяснение

0.3 == 3 * 0.1
False
Из-за погрешности чисел с плавающей точкой: 3 * 0.1 != 0.3 (в двоичной арифметике).

numpy.nan - numpy.nan
nan
Любая операция с nan даёт nan.

numpy.nan == numpy.nan
False
Согласно стандарту IEEE 754, nan не равно самому себе.

numpy.inf > numpy.nan
False
Любое сравнение с nan возвращает False, даже если логически кажется иначе.

numpy.nan in set([numpy.nan])
True
В Python set использует хэширование. Хотя nan != nan, они могут иметь одинаковый хэш, поэтому in может вернуть True. На практике — зависит от реализации, но в NumPy/Python часто True.

numpy.isnan(numpy.nan)
True
Это специальная функция для проверки на nan.

0 * numpy.nan
nan
Умножение любого числа на nan даёт nan.

'''

False
nan
False
False
True
True
nan


In [14]:
# Шаг 6_4_11

# 18.1

# Считайте число p.

# Создайте диагональную матрицу размера n*n. На главной диагонали должны быть числа от 1 до p.

# Сохраните матрицу в переменную Z.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

import numpy as np
n = int(input())

x = np.arange(n) + 1

Z = np.diag(x)

print(Z)

# Дока: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.diag.html
# Дока: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.arange.html



[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [24]:
# Шаг 6_4_12
import numpy as np

x, k = list(map(int, input().split()))
# print(x, k)

d = np.arange(k) + 1
# print(d)

Z = np.diag(d, x)

print(Z)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [45]:
# Шаг 6_4_13

# 19 (21)

# Считайте 2 числа: n, m.

# Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.
#   - 0 — "чёрное"
#   - 1 — "белое"

# Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0).

# Матрицу сохраните в переменную Z.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

# Решение не оптимальное (долгое)

import numpy as np

n, m = list(map(int, input().split()))

Z = np.zeros((n,m))
# print(Z)

for i in range(n):
    for j in range(m):
        if (i + j) % 2 == 1:
            Z[i,j] = 1
print(Z)






[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [80]:
import numpy as np

n, m = list(map(int, input().split()))

a = np.array([[0,1],[1,0]], dtype = float)
# print(a)

Z = np.tile(a,((n-1)//2+1, (m-1)//2+1))
# print(Z)
if n % 2 == 1:
    Z = Z[:n, :]
if m % 2 == 1:
    Z = Z[:, :m]

print(Z)

[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [85]:

import numpy as np

n, m = list(map(int, input().split()))

Z = np.ones((n,m))
# print(Z)
Z[::2, ::2] = 0
Z[1::2, 1::2] = 0
print(Z)

[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [125]:
# Шаг 6_4_14

# 20

# Если у нас есть матрица (или numpy массив большей размерности), то её можно представить в линейном виде:
#   [[0, 1, 2, 3],
#    [4, 5, 6, 7],
#    [8, 9, 10, 11]] → [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# Идея в том, что можно каждому элементу матрицы поставить в соответствие индекс.

# Функция numpy.unravel_index проводит обратную операцию — по индексу элемента определяет его "координаты" в матрице.

# Даны:
#   - индекс i
#   - numpy массив Z

# Определите "координаты" элемента с индексом i в Z и выведите кортеж с координатами на печать.

# Примечание. В этой задаче не нужно ничего считывать. i и Z уже заполнены.

import numpy as np

i = 4
Z = np.array([[[ 1,  2],
        [ 3,  4]],

       [[11, 12],
        [13, 14]]])
print(Z.shape)
print(np.unravel_index(i, Z.shape))

# Дока: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.unravel_index.html


(2, 2, 2)
(np.int64(1), np.int64(0), np.int64(0))


In [126]:
# В дополнение:
k = list(Z.shape)
tot = 1
for j in k:
    tot =  tot * j
print(tot)
Z1 = Z.reshape(1,tot)
print(Z1)
print(Z1.shape)
np.unravel_index(i, Z1.shape)


8
[[ 1  2  3  4 11 12 13 14]]
(1, 8)


(np.int64(0), np.int64(4))