In [2]:
# Шаг 6_6_1

# Numpy-100 (задачи 31-34, 37-40)

# Урок создан на основании известного сборника задач Numpy-100 - https://github.com/rougier/numpy-100

# Постарайтесь не подглядывать в ответы. =)


In [ ]:
from platform import version

# Шаг 6_6_2

# 31

# # Suicide mode on

# В Numpy можно предусмотреть различное поведение в случае ошибок (а не только то, что мы наблюдали в задаче 28). Для этого используется функция https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.seterr.html

# Отключите вывод всех ошибок (это довольно опасное поведение)

'''
# Не стал запускать код, это слишком опасно
import numpy as np

old_settings = np.seterr(all='ignore')  #seterr to known value
np.seterr(over='raise')

try:
    ZeroDivisionError
except:
    print("Кажется, я удачно поделил на 0 и не получил ошибок")
'''

In [ ]:
'''
# То, что написано в официальной доке:
>>> old_settings = np.seterr(all='ignore')  #seterr to known value
>>> np.seterr(over='raise')
{'over': 'ignore', 'divide': 'ignore', 'invalid': 'ignore',
 'under': 'ignore'}
>>> np.seterr(**old_settings)  # reset to default
{'over': 'raise', 'divide': 'ignore', 'invalid': 'ignore',
 'under': 'ignore'}
'''

In [2]:
# Шаг 6_6_3

import numpy as np

np.sqrt(-1) == np.emath.sqrt(-1)

# np.sqrt(-1) вызывает RuntimeWarning: invalid value encountered in sqrt. Функция np.sqrt не работает с отрицательными числами/
# Оно вернёт False

C:\Users\user\AppData\Local\Temp\ipykernel_15532\4237430821.py:5: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [13]:
# Шаг 6_6_4

# 33

# Изучите работу с датами (https://docs.scipy.org/doc/numpy-1.15.0/reference/arrays.datetime.html) и выберите верные утверждения:

# Отметьте верные ячейки.

import numpy as np

np.datetime64('today')
# Дата сегодня

np.datetime64('2025-12-23')

In [4]:
np.datetime64('nat')
# not-a-time

np.datetime64('NaT')

In [11]:
np.show_runtime()
# Узнать версию numpy (для справки)

[{'numpy_version': '2.2.6',
  'python': '3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='WIN-76SDQ64TH8B', release='11', version='10.0.26100', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': []}},
 {'architecture': 'SkylakeX',
  'filepath': 

In [14]:
np.datetime64('tomorrow')
# ValueError

ValueError: Error parsing datetime string "tomorrow" at position 0

In [15]:
np.datetime64('today')-1
# Дата вчера

np.datetime64('2025-12-22')

In [16]:
np.datetime64('today')+1
# Дата завтра

np.datetime64('2025-12-24')

In [17]:
np.datetime64('nat')+1
# not-a-time

np.datetime64('NaT')

In [18]:
np.datetime64('yesterday')
# ValueError

ValueError: Error parsing datetime string "yesterday" at position 0

In [19]:
np.datetime64('nat')-1
# not-a-time

np.datetime64('NaT')

In [4]:
# Шаг 6_6_5

# 34

# 1-я входная строка — год (опционально месяц и день) в формате ISO начала отсчёта
# 2-я входная строка — год (опционально месяц и день) в формате ISO окончания отсчёта

# Составьте список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).

# Результат должен представлять из себя список дат в формате ISO.

# Пример - 2005-02-25, где:
#   - 2005 — год
#   - 02 — месяц
#   - 25 — день

# Запишите результат в переменную Z.

import numpy as np

str1 = str(input())
str2 = str(input())

Z = np.arange(str1, str2, dtype = 'datetime64[D]')

print(Z)

# Ссылка на доку: https://docs.scipy.org/doc/numpy-1.15.0/reference/arrays.datetime.html#:~:text=The%20datetime%20type%20works%20with%20many%20common%20NumPy%20functions%2C%20for%20example%20arange%20can%20be%20used%20to%20generate%20ranges%20of%20dates.

['2019-01-01' '2019-01-02' '2019-01-03' '2019-01-04' '2019-01-05'
 '2019-01-06' '2019-01-07' '2019-01-08']


In [8]:
# Шаг 6_6_6

# 36

# Существует по крайней мере 5 способов получить из вектора случайных float чисел вектор чисел только с целой частью:

# 1. Целочисленное деление и векторные операции
# 2. Округление "вниз"
# 3. Округление "вверх" и вычет 1 (важно, что этот способ работает только для "случайных" чисел. Если число УЖЕ целое, то такая манипуляция приведёт к получению числа на 1 меньше исходного, т.е. ошибке)
# 4. Приведение к целочисленному типу
# 5. "Усечение" или округление в сторону нуля с помощью функции https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.trunc.html



3.0


In [12]:
import numpy as np

np.random.seed(42)
Z = np.random.uniform(0,10,10)
print(Z)



[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864  1.5599452
 0.58083612 8.66176146 6.01115012 7.08072578]


In [13]:
Z - Z%1

array([3., 9., 7., 5., 1., 1., 0., 8., 6., 7.])

In [14]:
np.floor(Z)

array([3., 9., 7., 5., 1., 1., 0., 8., 6., 7.])

In [15]:
np.ceil(Z)-1

array([3., 9., 7., 5., 1., 1., 0., 8., 6., 7.])

In [16]:
Z.astype(int)

array([3, 9, 7, 5, 1, 1, 0, 8, 6, 7])

In [17]:
np.trunc(Z)

array([3., 9., 7., 5., 1., 1., 0., 8., 6., 7.])

In [53]:
# Шаг 6_6_7

# 37.1

# На вход подаётся 2 строки:
#   - 1-я строка содержит 2 натуральных числа: n, m
#   - 2-я строка содержит число k

# Создайте матрицу размера n*m такую, что каждая её строка содержит числа от k до k+m-1 (с шагом 1).

# Ответ запишите в переменную Z.

import numpy as np

n,m = list(map(int, input().split()))
k = int(input())
# print(n,m,k)

Z = np.tile(np.arange(k, k+m),(n,1)).astype(float)
Z

array([[-5., -4., -3., -2.],
       [-5., -4., -3., -2.],
       [-5., -4., -3., -2.],
       [-5., -4., -3., -2.],
       [-5., -4., -3., -2.]])

In [51]:

np.tile(np.arange(5),(4,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [58]:
# Шаг 6_6_8

# 37.2

# На вход подаётся 2 строки:
#   - 1-я строка содержит 2 натуральных числа: n, m
#   - 2-я строка содержит число k

# Создайте матрицу размера n*m такую, что каждый её столбец содержит числа от k до k+n-1 (с шагом 1).

# Ответ запишите в переменную Z.

import numpy as np

n,m = list(map(int, input().split()))
k = int(input())
# print(n,m,k)

Z = np.tile(np.arange(k, k+n),(m,1)).astype(float).transpose()
Z

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.]])

In [64]:
# Решение через reshape:

import numpy as np

n,m = list(map(int, input().split()))
k = int(input())
# print(n,m,k)

Z = np.full((n,m),k, dtype=float) + np.arange(n).reshape(n,1)
Z

array([[-5., -5., -5., -5.],
       [-4., -4., -4., -4.],
       [-3., -3., -3., -3.],
       [-2., -2., -2., -2.],
       [-1., -1., -1., -1.]])

In [76]:
# Шаг 6_6_9

# 38

# Переменная V содержит итерируемый объект.

# Превратите его в одномерный numpy массив и сохраните в переменную Z. Массив будет содержать только числа типа float.

# Sample Input 1:
#   V = range(10)
# Sample Output 1:
#   [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

# Sample Input 2:
#   V = map(numpy.sin, range(10))
# Sample Output 2:
#   [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
#    -0.2794155   0.6569866   0.98935825  0.41211849]

# Sample Input 3:
#   V = {1:2, 3:4}
# Sample Output 3:
#   [1. 3.]


V = range(10)

import numpy as np

Z = np.fromiter(V, dtype = float)
Z


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
# Шаг 6_6_10

# 39.1 (деление отрезка на N+1 часть)

# На вход подаются 3 числа (каждое с новой строки):
#   - start
#   - stop
#   - n

# Составьте список (numpy.array) из n точек на отрезке (start, stop), попарно равноудалённых друг от друга и от концов отрезка (т.е. разделите отрезок на n+1 часть).

# Округлите значения точек до 3 знака после запятой.

# Результат сохраните в переменную Z.

import numpy as np

start = int(input())
stop = int(input())
n = int(input())

Z = np.round(np.linspace(start, stop, n+1, endpoint = False)[1:], 3)

print(Z)

# Дока: https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [17]:
# Шаг 6_6_11

# 39.2

# На вход подаются 3 числа (каждое с новой строки):
#   - start
#   - stop
#   - n

# Составьте список из n точек на отрезке [start, stop] в геометрической прогрессии, включая start и stop.

# Округлите значения точек до 3 знака после запятой.

# Результат сохраните в переменную Z.

import numpy as np

start = int(input())
stop = int(input())
n = int(input())

Z = np.geomspace(start, stop, n).round(3)

print(Z)

# Дока: https://numpy.org/doc/stable/reference/generated/numpy.geomspace.html#numpy.geomspace

array([  1.   ,   3.162,  10.   ,  31.623, 100.   ])

In [26]:
# Шаг 6_6_12

# 40

# Считайте 2 числа:
#   - seed
#   - n

# С помощью Numpy сгенерируйте n случайных чисел из интервала (0, 1) с фиксированным seed.
# Отсортируйте их по возрастанию и сохраните в переменную Z.

# Дока : https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.seed.html
# Дока: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html

import numpy as np

seed = int(input())
n = int(input())

np.random.seed(seed)

Z = np.sort(np.random.random_sample((n,)))
print(Z)


[0.20671916 0.22199317 0.48841119 0.87073231 0.91861091]


In [29]:
import numpy as np

seed = int(input())
n = int(input())

np.random.seed(seed)

Z = np.sort(np.random.uniform(0, 1, n))
print(Z)

[0.20671916 0.22199317 0.48841119 0.87073231 0.91861091]
