In [2]:
# Шаг 6_2_1

# Темы семинара 3

# Математика:
#   - Введение - Линейная независимость векторов, ранг матрицы, ранг по строкам и столбцам.
#   - Задача 1 - Линейная независимость 3 векторов
#   - Задача 2 - Максимальное число линейно независимых векторов из набора 6
#   - Задача 3 - Какие из векторов образуют базис
#   - Норма и метрика. Что это и зачем нужно?
#   - Косинусное расстояние и близость


In [ ]:
# Шаг 6_2_2

Линейная независимость векторов

In [1]:
import numpy as np

e1 = np.array([1., 0., 0.])
e2 = np.array([0., 5., 0.])


In [6]:
-3*e1 + 2*e2

array([-3., 10.,  0.])

In [8]:
0*e1 + 0*e2 # не интересует, тривиальная комбинация

array([0., 0., 0.])

In [5]:
a = np.array([-3., 10., 0.])


In [7]:
3*e1 - 2*e2 + 1*a

array([0., 0., 0.])

In [11]:
a == -3*e1 + 2*e2


array([ True,  True,  True])

Линейная независимость векторов и ранг матрицы

In [13]:
M = np.array([e1, e2, a])
M

array([[ 1.,  0.,  0.],
       [ 0.,  5.,  0.],
       [-3., 10.,  0.]])

In [16]:
np.linalg.matrix_rank(M)

np.int64(2)

Ранг матрицы по строкам и столбцам

In [17]:
b1, b2, b3 = M[:, 0], M[:, 1], M[:, 2]

In [19]:
b1

array([ 1.,  0., -3.])

In [21]:
0*b1 + 0*b2 + 1*b3

array([0., 0., 0.])

В матрице число линейно независимых строк равно числу линейно независимых столбцов

Линейная независимость векторов

In [ ]:
# Шаг 6_2_3

# 1. Рассмотрим 3 вектора:
#   [a]   [b]   [c]
#   [0] , [d] , [e]
#   [0]   [0]   [f]

# Известно, что три числа из набора чисел {a, b, c, d, e, f} равны нулю, а оставшиеся три — отличны от нуля.

# Выберите варианты, при которых эти векторы линейно зависимы.
#
# 1. a=0, b=0, f=0
# 2. b=0, e=0, f=0
# 3. c=0, d=0, f=0
# 4. b=0, c=0, e=0
# 5. a=0, b=0, d=0
# 6. a=0, e=0, f=0

In [26]:
import numpy as np

M = np.array([
    #a, b, c, d, e, f
    [0, 0, 1, 1, 1, 0],
    [1, 0, 1, 1, 0, 0],
    [1, 1, 0, 0, 1, 0],
    [1, 0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1, 1],
    [0, 1, 1, 0, 0, 0]
])
M

array([[0, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0, 0]])

In [29]:
for a,b,c,d,e,f in M:
    N = np.array([
        [a,0,0],
        [b,d,0],
        [c,e,f]
    ])
    print(N)
    print(np.linalg.matrix_rank(N))
    print(a,b,c,d,e,f)

[[0 0 0]
 [0 1 0]
 [1 1 0]]
2
0 0 1 1 1 0
[[1 0 0]
 [0 1 0]
 [1 0 0]]
2
1 0 1 1 0 0
[[1 0 0]
 [1 0 0]
 [0 1 0]]
2
1 1 0 0 1 0
[[1 0 0]
 [0 1 0]
 [0 0 1]]
3
1 0 0 1 0 1
[[0 0 0]
 [0 0 0]
 [1 1 1]]
1
0 0 1 0 1 1
[[0 0 0]
 [1 0 0]
 [1 0 0]]
1
0 1 1 0 0 0


In [ ]:
# только в четвёртом варианте получилось три (ранг матрицы), поэтому только в варианте 4 вектора линейно независимы, в остальных - зависимы

Число независимых векторов из набора

In [30]:
# Шаг 6_2_4

# 2. Найдите среди заданных шести векторов вида
#   [1]   [1]   [1]   [0]   [0]   [0]
#   [-1], [0], [0], [1], [1], [0]
#   [0]   [-1]  [0]   [-1]  [0]   [1]
#   [0]   [0]   [-1]  [0]   [-1]  [-1]

# наибольшее количество линейно независимых векторов.

In [32]:

import numpy as np

M = np.array([
    [1, -1, 0, 0],
    [1, 0, -1, 0],
    [1, 0, 0, -1],
    [0, 1, -1, 0],
    [0, 1, 0, -1],
    [0, 0, 1, -1]
])
M

array([[ 1, -1,  0,  0],
       [ 1,  0, -1,  0],
       [ 1,  0,  0, -1],
       [ 0,  1, -1,  0],
       [ 0,  1,  0, -1],
       [ 0,  0,  1, -1]])

In [33]:
np.linalg.matrix_rank(M)

np.int64(3)

In [ ]:
# Шаг 6_2_5

Какие из векторов образуют базис

In [ ]:
# 3. Какие из нижеперечисленных векторов образуют базис в трёхмерном пространстве ℝ³?

# Hint. Базис образуют линейно независимые вектора, из линейной комбинации которых можно получить любой вектор в пространстве данной размерности.

# 1. (1, 2, 0), (0, 1, -1)
# 2. (1, 1, -1), (2, 3, 4), (4, 1, -1), (0, 1, -1)
# 3. (1, 2, 2), (-1, 2, 1), (0, 8, 0)
# 4. (1, 2, 2), (-1, 2, 1), (0, 8, 6)

In [45]:
import numpy as np

# нужно число векторов совпадающих с размерностью пространства, поэтому 2 и 4 вектора не смогут образовать базис

MM = np.array([
    [
        (1, 2, 2),
        (-1, 2, 1),
        (0, 8, 0),
    ],
    [
        (1, 2, 2),
        (-1, 2, 1),
        (0, 8, 6),
    ]
])

MM[0]

array([[ 1,  2,  2],
       [-1,  2,  1],
       [ 0,  8,  0]])

In [46]:
for M in MM:
    print(M)
    print(np.linalg.matrix_rank(M))
    # ранг матрицы должен совпадать с числом векторов, тогда эти вектора образуют базис (в данном случае в трёхмерном пространстве)

[[ 1  2  2]
 [-1  2  1]
 [ 0  8  0]]
3
[[ 1  2  2]
 [-1  2  1]
 [ 0  8  6]]
2


In [47]:
# Ответ: #3  (1, 2, 2), (-1, 2, 1), (0, 8, 0)

In [ ]:
# Шаг 6_2_6

Норма и метрика. Что это? Зачем нужна метрика?

In [4]:
# Норма и метрика:

#   - Интуитивный бытовой пример нормы — длина
#   - Интуитивный пример метрики — расстояние

# Зачем нужна метрика?

# Рассмотрим датасет "Red Wine Dataset" https://www.kaggle.com/piyushgoyal443/red-wine-dataset

# Пример загрузки:
import pandas as pd
D = pd.read_csv('wineQualityReds.csv')
D.head(15)

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
0            1            7.4             0.700         0.00             1.9   
1            2            7.8             0.880         0.00             2.6   
2            3            7.8             0.760         0.04             2.3   
3            4           11.2             0.280         0.56             1.9   
4            5            7.4             0.700         0.00             1.9   
5            6            7.4             0.660         0.00             1.8   
6            7            7.9             0.600         0.06             1.6   
7            8            7.3             0.650         0.00             1.2   
8            9            7.8             0.580         0.02             2.0   
9           10            7.5             0.500         0.36             6.1   
10          11            6.7             0.580         0.08             1.8   
11          12            7.5             0.500         0.36             6.1   
12          13            5.6             0.615         0.00             1.6   
13          14            7.8             0.610         0.29             1.6   
14          15            8.9             0.620         0.18             3.8   

    chlorides  free.sulfur.dioxide  total.sulfur.dioxide  density    pH  \
0       0.076                 11.0                  34.0   0.9978  3.51   
1       0.098                 25.0                  67.0   0.9968  3.20   
2       0.092                 15.0                  54.0   0.9970  3.26   
3       0.075                 17.0                  60.0   0.9980  3.16   
4       0.076                 11.0                  34.0   0.9978  3.51   
5       0.075                 13.0                  40.0   0.9978  3.51   
6       0.069                 15.0                  59.0   0.9964  3.30   
7       0.065                 15.0                  21.0   0.9946  3.39   
8       0.073                  9.0                  18.0   0.9968  3.36   
9       0.071                 17.0                 102.0   0.9978  3.35   
10      0.097                 15.0                  65.0   0.9959  3.28   
11      0.071                 17.0                 102.0   0.9978  3.35   
12      0.089                 16.0                  59.0   0.9943  3.58   
13      0.114                  9.0                  29.0   0.9974  3.26   
14      0.176                 52.0                 145.0   0.9986  3.16   

    sulphates  alcohol  quality  
0        0.56      9.4        5  
1        0.68      9.8        5  
2        0.65      9.8        5  
3        0.58      9.8        6  
4        0.56      9.4        5  
5        0.56      9.4        5  
6        0.46      9.4        5  
7        0.47     10.0        7  
8        0.57      9.5        7  
9        0.80     10.5        5  
10       0.54      9.2        5  
11       0.80     10.5        5  
12       0.52      9.9        5  
13       1.56      9.1        5  
14       0.88      9.2        5

In [20]:
# Какой из алгоритмов лучше: Predict1 или Predict2?

# Если представить правильные значения и предсказания обоих алгоритмов в виде векторов:
#   - Y_ист = [5, 5, 5, 6, 5, 5, 5, 7, 7, 5, 5, 5, 5, 5, 5, 5, 7, 5, 4, 6, ...]
#   - P_pr1 = [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ...]
#   - P_pr2 = [5, 6, 5, 6, 5, 5, 5, 7, 7, 5, 5, 6, 5, 5, 5, 5, 7, 7, 5, 5, ...]

# то в метрике (т.е. расстояние) между вектором предсказания и вектором правильных ответов будет мерой качества алгоритма.
# Чем ближе значение прогнозного и истинного значения для каждой точки, тем точнее алгоритм, тем меньше метрика, тем меньше расстояние между векторами.

# Метрики:
#   - Манхэттонская метрика: ||p - y|| = Σ|p_i - y_i|
#   - Евклидова метрика: ||p - y||₂ = √Σ(p_i - y_i)²

import numpy as np

# Проверяем 2 неких алгоритма, предсказывающих качество вина

Y = np.array([5, 5, 5, 6, 5, 5, 5, 7, 7, 5, 5, 5, 5, 5, 5, 5, 7, 5, 4, 6, 6])
P1 = np.array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
P2 = np.array([5, 6, 5, 6, 5, 5, 5, 7, 7, 5, 5, 6, 5, 6, 5, 5, 5, 7, 7, 5, 5])

In [21]:
# Манхэттонская метрика
print(sum(abs(P1 - Y)))


10


In [22]:
print(sum(abs(P2 - Y)))

12


In [23]:
# Евклидова метрика
print((sum((P1 - Y)**2))**0.5)

4.0


In [24]:
print((sum((P2 - Y)**2))**0.5)

4.69041575982343


In [25]:
# Получается, вторая модель хуже, чем первая, даже несмотря на то, что первая ставит только "пятёрки".

In [ ]:
# Шаг 6_2_7

Косинусное расстояние. Косинусная близость

In [ ]:
# Косинусное расстояние, Косинусная близость

# Косинусная близость или просто косинус угла между 2 векторами:
#   (u · v) / (||u||₂ ||v||₂)

# Косинусное расстояние:
#   1 - (u · v) / (||u||₂ ||v||₂)

# Чем ближе 2 вектора:
#   - тем больше косинус (cos(0°) = 1)
#   - тем меньше косинусное расстояние (1 - cos(0°) = 0)

In [2]:
import numpy as np

Y = np.array([5, 5, 5, 6, 5, 5, 5, 7, 7, 5, 5, 5, 5, 5, 5, 5, 7, 5, 4, 6, 6])
P1 = np.array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
P2 = np.array([5, 6, 5, 6, 5, 5, 5, 7, 7, 5, 5, 6, 5, 6, 5, 5, 5, 7, 7, 5, 5])

np.dot(Y, P1)

np.int64(565)

In [3]:
np.linalg.norm(Y)

np.float64(24.919871588754223)

In [5]:
(np.dot(Y, P1)) / (np.linalg.norm(Y) * np.linalg.norm(P1))

np.float64(0.9895163989446487)

In [6]:
(np.dot(Y, P2)) / (np.linalg.norm(Y) * np.linalg.norm(P2))

np.float64(0.9834685029384934)

In [7]:
# Косинусное расстояние (есть специальная функция)
from scipy.spatial.distance import cosine

In [8]:
cosine(Y, P1)

np.float64(0.0104836010553514)

In [10]:
cosine(Y, P2)

np.float64(0.016531497061506806)