In [ ]:
# Шаг 7_2_1

# Спектральное и сингулярное разложение матриц

# 1. Спектральное разложение матриц
# 2. Что такое квадратичные формы
# 3. Упрощение квадратичных форм с помощью спектрального разложения
# 4. Сингулярное разложение матриц
# 5. Связь между спектральным и сингулярным разложениями (частный случай для квадратных матриц)

In [10]:
# Шаг 7_2_2

# Спектральное разложение матрицы

import numpy as np

np.set_printoptions(precision = 2, suppress = True)

A = np.array([[1.0, 2.0, -1.0], [2.0, 2.0, 5.0], [-1.0, 5.0, -3.0]])
A

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])

In [11]:
v, w = np.linalg.eigh(A)

In [12]:
v

array([-6.5753629 ,  1.14911837,  5.42624453])

In [13]:
w

array([[-0.24709   ,  0.92927297, -0.27458749],
       [ 0.5304425 , -0.10742791, -0.84088643],
       [-0.81091139, -0.3534275 , -0.46638151]])

In [14]:
D = np.diag(v)
D

array([[-6.5753629 ,  0.        ,  0.        ],
       [ 0.        ,  1.14911837,  0.        ],
       [ 0.        ,  0.        ,  5.42624453]])

In [15]:
S = w.T
S

array([[-0.24709   ,  0.5304425 , -0.81091139],
       [ 0.92927297, -0.10742791, -0.3534275 ],
       [-0.27458749, -0.84088643, -0.46638151]])

In [16]:
S.T

array([[-0.24709   ,  0.92927297, -0.27458749],
       [ 0.5304425 , -0.10742791, -0.84088643],
       [-0.81091139, -0.3534275 , -0.46638151]])

In [17]:
np.dot(S.T, S)

array([[1.00000000e+00, 5.80413027e-17, 1.16447902e-16],
       [5.80413027e-17, 1.00000000e+00, 4.58528324e-17],
       [1.16447902e-16, 4.58528324e-17, 1.00000000e+00]])

In [18]:
np.dot(np.dot(S.T, D), S)

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])

In [13]:
# Шаг 7_2_3

# Квадратичные формы

# P(x,y,z) = x**2 + 2*y**2 - 3*z**2 + 4*x*y + 10*y*z - 2*x*z

#                   (1  2 -1  (x
# P(x,y,z) = (x y z) 2  2  5   y
#                   -1  5 -3 ) z)


In [14]:
# Шаг 7_2_4

# Выберите все функции, являющиеся квадратичными формами

# Выберите все подходящие ответы из списка:

# - P(x) = 8x³ - 4x² + 2x - 1
# - P(x, y) = x⁴ + y³ + x² + y + 42
# - P(x) = 9x² - 6x + 1
# + P(x) = x²
# + P(x, y) = x² + 2xy + y²
# + P(x, y) = (3x - 2y)²
# - P(x) = (3x - 1)²
# - P(x, y) = x² + 2xy + y² + 3x + 3y + 4



In [15]:
# Шаг 7_2_5

# Выберите все функции, являющиеся квадратичными формами

# В данном вопросе есть небольшой подвох.

# Выберите все подходящие ответы из списка:

# + P(x, y) = (x + y)²
# + P(x, y) = x²
# + P(x, y) = x² + y²
# + P(x, y) = x² + xy + y²
# + P(x, y) = xy


In [ ]:
# Шаг 7_2_6

# Какая из квадратичных форм соответствует матричной записи:

# P(w, x, y, z) = (w  x  y  z) ·
#   ⎡ 1   0   2  -1⎤
#   ⎢ 0  -2   3   0⎥
#   ⎢ 2   3   0   0⎥
#   ⎣-1   0   0   1⎦
# · (w, x, y, z)ᵀ

# Выберите один вариант из списка:
# + P(w, x, y, z) = w² - 2x² + z² + 4wy - 2wz + 6xy
# - P(w, x, y, z) = x² - 2y² + z² + 4wy - 2wz + 6xy
# - P(w, x, y, z) = w² - 2x² + y² + z² + 4wy - 2wz + 6xy
# - P(w, x, y, z) = x² - 2y² + w² + 4xz - 2xw + 6yz
# - P(w, x, y, z) = w² - 2x² + z² + 2wy - wz + 3xy
# - P(w, x, y, z) = w² - 2x² + z² + wx + 4wy - 2wz + 6xy + xz + yz

In [20]:
# Шаг 7_2_7

import numpy as np

np.set_printoptions(precision = 2, suppress = True)

A = np.array([[1.0, 2.0, -1.0], [2.0, 2.0, 5.0], [-1.0, 5.0, -3.0]])

v,w = np.linalg.eigh(A)

D = np.diag(v)
s = w.T

print('D = \n', D)
print('S = \n', S)

D = 
 [[-6.58  0.    0.  ]
 [ 0.    1.15  0.  ]
 [ 0.    0.    5.43]]
S = 
 [[-0.25  0.53 -0.81]
 [ 0.93 -0.11 -0.35]
 [-0.27 -0.84 -0.47]]


In [21]:
# Шаг 7_2_8

# Сингулярное разложение матрицы

import numpy as np

np.set_printoptions(precision = 2, suppress = True)

X = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
X

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [24]:
U, s, W = np.linalg.svd(X)

In [25]:
U

array([[ 0.17056501,  0.15680918, -0.53077508, -0.79905375, -0.16158397],
       [ 0.39287016, -0.52933945,  0.6134793 , -0.43375771,  0.03082495],
       [-0.14366152, -0.82449256, -0.52379105,  0.14049848,  0.07400343],
       [ 0.88843702,  0.06074346, -0.24655277,  0.37755832, -0.06042632],
       [ 0.08125046,  0.10831843, -0.08231425, -0.10524851,  0.98173958]])

In [27]:
V = W.T
V

array([[ 0.07116451, -0.36737824, -0.92734505],
       [ 0.71702467,  0.66514082, -0.20847855],
       [ 0.69340553, -0.65009301,  0.31075368]])

In [28]:
s

array([8.82486885, 6.14060608, 2.53271528])

In [30]:
D = np.zeros_like(X, dtype = float)
D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
D[np.diag_indices(min(X.shape))] = s
D

array([[8.82486885, 0.        , 0.        ],
       [0.        , 6.14060608, 0.        ],
       [0.        , 0.        , 2.53271528],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [34]:
np.dot(U.T, U)

array([[ 1.00000000e+00,  9.43922534e-17, -2.03924253e-16,
        -4.16117852e-17, -8.57750402e-18],
       [ 9.43922534e-17,  1.00000000e+00,  2.61279341e-16,
         7.31682679e-17,  1.77052395e-17],
       [-2.03924253e-16,  2.61279341e-16,  1.00000000e+00,
        -1.69490966e-16, -7.11991378e-17],
       [-4.16117852e-17,  7.31682679e-17, -1.69490966e-16,
         1.00000000e+00, -4.00102757e-17],
       [-8.57750402e-18,  1.77052395e-17, -7.11991378e-17,
        -4.00102757e-17,  1.00000000e+00]])

In [36]:
np.dot(V.T, V)

array([[ 1.00000000e+00,  2.48722557e-17, -1.16098057e-17],
       [ 2.48722557e-17,  1.00000000e+00, -6.33614567e-17],
       [-1.16098057e-17, -6.33614567e-17,  1.00000000e+00]])

In [37]:
np.dot(U, D)

array([[ 1.50521386,  0.9629034 , -1.34430215],
       [ 3.46702765, -3.25046504,  1.5537684 ],
       [-1.26779411, -5.06288401, -1.32661359],
       [ 7.8403402 ,  0.37300164, -0.62444796],
       [ 0.71702467,  0.66514082, -0.20847855]])

In [38]:
np.dot(np.dot(U, D), V.T)

array([[ 1.00000000e+00,  2.00000000e+00,  5.13921141e-16],
       [ 1.25369098e-15, -2.94364984e-15,  5.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  6.00000000e+00,  5.00000000e+00],
       [-1.33610390e-16,  1.00000000e+00, -9.73661964e-17]])

In [1]:
# Шаг 7_2_9

# Связь между спектральным и сингулярным разложением

import numpy as np

np.set_printoptions(precision = 2, suppress = True)

A = np.array([[1.0, 2.0, -1.0], [2.0, 2.0, 5.0], [-1.0, 5.0, -3.0]])

v,w = np.linalg.eigh(A)

D_sp = np.diag(v)
S_sp = w.T

print(S_sp.T, D_sp, S_sp, sep = '\n\n')



[[-0.25  0.93 -0.27]
 [ 0.53 -0.11 -0.84]
 [-0.81 -0.35 -0.47]]

[[-6.58  0.    0.  ]
 [ 0.    1.15  0.  ]
 [ 0.    0.    5.43]]

[[-0.25  0.53 -0.81]
 [ 0.93 -0.11 -0.35]
 [-0.27 -0.84 -0.47]]


In [2]:
np.dot(np.dot(S_sp.T, D_sp), S_sp)

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])

In [7]:
import numpy as np

np.set_printoptions(precision = 2, suppress = True)

A = np.array([[1.0, 2.0, -1.0], [2.0, 2.0, 5.0], [-1.0, 5.0, -3.0]])

U_sin, s, W = np.linalg.svd(A)
D_sin = np.zeros_like(A, dtype = float)
D_sin[np.diag_indices(min(A.shape))] = s

V_sin = W.T

print(U_sin, D_sin, V_sin.T, sep = '\n\n')

[[ 0.25  0.27 -0.93]
 [-0.53  0.84  0.11]
 [ 0.81  0.47  0.35]]

[[6.58 0.   0.  ]
 [0.   5.43 0.  ]
 [0.   0.   1.15]]

[[-0.25  0.53 -0.81]
 [ 0.27  0.84  0.47]
 [-0.93  0.11  0.35]]


In [9]:
np.dot(np.dot(U_sin, D_sin), V_sin.T)

array([[ 1.,  2., -1.],
       [ 2.,  2.,  5.],
       [-1.,  5., -3.]])

In [ ]:
#Отличается порядок цифр в массивах и знаки в некоторых местах