In [2]:
# Шаг 6_3_1

# Что такое Numpy?

# NumPy — библиотека с открытым исходным кодом для Python, реализующая множество математических операций для работы с векторами, матрицами и массивами.
# Важное преимущество NumPy перед собственной реализацией массивов (например на списках) — это векторные операции, которые происходят гораздо быстрее, последовательных.

# Фактически, NumPy — это основная математическая библиотека для работы с данными (если вы решаете задачи машинного обучения или анализа данных).
# Именно NumPy, а не встроенный Math.

# NumPy лежит в основе других важных библиотек: Pandas (работа с табличными данными), SciPy (работы с методами оптимизации и научными расчётами), Matplotlib (построение графиков) и т.д.

# Именно поэтому важно уметь работать с NumPy, чтобы быстро применять векторные операции, а не проходить по всему массиву в цикле for.

# В рамках этой части практикума вы можете решить задачи на базе задачника Numpy-100,
# а подсказки в виде ссылок на документацию или небольшие пояснения вы можете найти в комментариях к задачам.

# Также рекомендую познакомиться с документацией по библиотеке https://docs.scipy.org/doc/


In [ ]:
# Шаг 6_3_2

# Numpy-100 (задачи 1-10)

# Урок создан на основании известного сборника задач Numpy-100 - https://github.com/rougier/numpy-100

# Постарайтесь не подглядывать в ответы. =)



In [ ]:
# Шаг 6_3_3

# 1

# Импортируйте модуль numpy как np

# Примечание. В этой задаче не нужно ничего считывать и ничего выводить на печать.

import numpy as np

In [ ]:
# Шаг 6_3_4

# У модулей Numpy и SciPy есть методы для вывода служебной информации помимо версии.
# Для этого используется файл __config__.py в корне пакета.
# Вы можете вызвать его с помощью метода show_config().

# Этот метод, так же как и атрибут __version__ применяется к самому модулю.

import numpy as np
np.show_config()

In [12]:
# Шаг 6_3_5

# 2

# Выведите на печать версию модуля numpy, используемую в текущий момент в песочнице Stepik.

# Sample Output:
# 1.14.1

import numpy
numpy.show_runtime()

[{'numpy_version': '2.2.6',
  'python': '3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='WIN-76SDQ64TH8B', release='11', version='10.0.26100', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': []}},
 {'architecture': 'SkylakeX',
  'filepath': 

In [19]:
import numpy as np
print(np.__version__)

2.2.6


In [21]:
# Шаг 6_3_6

# 3.1

# Считайте число n

# Создайте в переменной Z Numpy вектор из нулей длины n.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

import numpy as np

n = int(input())

Z = np.array([0.]*n)

# print(Z)

[0. 0. 0. 0. 0.]


In [36]:
# Шаг 6_3_7

# 3.2

# Считайте строку, где значения заданы через пробел: сначала shape, затем dtype.

# Последнее значение в строке может быть либо числом (тогда это последнее значение кортежа shape), либо строкой dtype.

#   - shape — атрибут, задающий размеры матрицы нулей (позволяет вернуть вектор-строку, вектор-столбец, матрицу, куб и т.д.)
#   - dtype — тип данных, использующихся для значений матрицы. По-умолчанию используется numpy.float64 (если dtype не указан).

# Создайте матрицу Z размера shape, со значениями типа dtype.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

# Черновик:

str = input().split()

print(str)

str_0 = str[:-1]
str_1 = str[-1]
print(str_0)
print(str_1)
str_0 = list(map(int, str_0))
print(str_0)
if str_1.isdigit():
    str_0.append(int(str_1))
else:
    d_type = str_1
print(str_0)

str_0 = tuple(str_0)

Z = np.zeros((str_0), dtype = d_type)

print(Z)


['2', '3', 'bool']
['2', '3']
bool
[2, 3]
[2, 3]
[[False False False]
 [False False False]]


In [45]:
# Итоговый ответ:

import numpy as np

str = input().split()

# print(str)

str_0 = str[:-1]
str_1 = str[-1]
# print(str_0)
# print(str_1)
str_0 = list(map(int, str_0))
# print(str_0)
if str_1.isdigit():
    str_0.append(int(str_1))
    d_type = np.float64
else:
    d_type = str_1
# print(str_0)

str_0 = tuple(str_0)

Z = np.zeros(str_0, dtype = d_type)

print(Z)

[0 0 0 0]


In [64]:
# Шаг 6_3_8

# 4

# Посчитайте размер матрицы Z в байтах и выведите его на печать.

# Чтобы узнать размер (в байтах) 1 элемента матрицы используйте атрибут https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ndarray.itemsize.html

# Примечание. В этой задаче не нужно ничего считывать — матрица Z уже заполнена.

import numpy as np

Z = np.zeros((10,10))
k = list(Z.shape)
# print(k)
tot = Z.itemsize
for i in k:
    tot =  tot * i

print(tot)

800


In [58]:
import numpy as np

Z = np.array([1,2,3], dtype=np.float64)
tot = Z.size * Z.itemsize
print(tot)

24


In [60]:
import numpy as np

def sizematrix(Z):
    print(Z.size * Z.itemsize)

sizematrix(np.zeros((10,10)))

800


In [6]:
# Шаг 6_3_9

# 5

# Выведите на печать встроенную документацию для функции add numpy, а потом объекта numpy.array.

import numpy

print(numpy.add.__doc__)

print(numpy.array.__doc__)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [2]:
# Шаг 6_3_10

# 6

# Считайте 2 числа:
#   - n — размер Numpy вектора
#   - x — координата элемента вектора, который должен быть равен 1. Остальные элементы вектора должны быть равны 0.

# Сохраните вектор в переменную Z.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

import numpy as np

n = int(input())
x = int(input())

Z = np.zeros((n,), dtype = float)
Z[x] = 1.0

print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
# Шаг 6_3_11

# 7

# Считайте 2 числа n, m.

# Создайте вектор Z состоящий из чисел от n до m с шагом 1.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

import numpy as np

n = int(input())
m = int(input())

Z = np.array(range(n, m+1, 1))
Z
# print(Z)



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [14]:
# Шаг 6_3_12

# 8

# Дан вектор Z.

# "Разверните" его.

# Примечание. В этой задаче не нужно ничего выводить на печать или считывать. Только развернуть уже созданный вектор Z.

import numpy as np

Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
Z

array([4, 3, 2, 1])

In [11]:
# Правильный ответ выглядит так:
import numpy as np

# Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
# Z

In [61]:
# Можно в принципе ещё через flip:
import numpy as np
Z = np.array([1, 2, 3, 4])

Z = np.flip(Z)
Z

array([4, 3, 2, 1])

In [46]:
# Шаг 6_3_13

# 9

# Считайте 3 числа:
#   - n — количество элементов матрицы
#   - m и k — размеры матрицы (число строк и столбцов соответственно)

# Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).

# Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется пустых мест.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

import numpy as np

n = int(input())
# tupl = input()
m, k = list(map(int, input().split()))

# print(tupl)
# print(type(tupl))
# print(m, k)
# print(type(m), type(k))
Z = np.array(range(n))
Z = Z.reshape(m,k)

Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
# Шаг 6_3_14

# 10.1

# Дан вектор Z.

# Запишите в переменную NonZeros индексы ненулевых элементов.

# Используйте функцию https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.nonzero.html

# Примечание. В этой задаче не нужно ничего считывать или выводить на печать. Вектор Z уже готов, просто создайте NonZeros.

import numpy as np

Z = [1, 2, 0, 0, 4, 0]

NonZerros = np.nonzero(Z)
NonZerros

(array([0, 1, 4]),)

In [ ]:
# Пример работы numpy.nonzero

'''
import numpy as np

a = np.array([[0, 1, 0],
              [2, 0, 3],
              [0, 4, 0]])

indices = np.nonzero(a)
print(indices)
# Вывод: (array([0, 1, 1, 2]), array([1, 0, 2, 1]))

indices[0] (строки): [0, 1, 1, 2]
indices[1] (столбцы): [1, 0, 2, 1]
Ненулевые элементы находятся в a[0, 1], a[1, 0], a[1, 2], a[2, 1]
'''



In [95]:
# Шаг 6_3_15

# 10.2

# Дана матрица чисел Z (Z может быть 1, 2 или даже 3 мерной).

# Выведите на печать список чисел из этой матрицы, которые больше 3.

import numpy as np

Z = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [0, 0, 9]])

Z = list(Z[np.nonzero(Z > 3)].tolist())

print(Z)

[4, 5, 6, 7, 8, 9, 9]


In [104]:
# Функция numpy.ravel() преобразует многомерный массив NumPy в одномерный (плоский) вектор

# Важно! ravel() убирает запятые в списке!
import numpy as np

Z = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [0, 0, 9]])

Z = Z.ravel()

print(Z)

[1 2 3 4 5 6 7 8 9 0 0 9]


In [105]:
import numpy as np
# Этот ответ не подходит, т.к. список без запятых
Z = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [0, 0, 9]])

Z = Z[np.nonzero(Z > 3)].ravel()

print(Z)

[4 5 6 7 8 9 9]


In [107]:
import numpy as np
Z = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [0, 0, 9]])
# Масло масляное по итогу
Z = list(Z[np.nonzero(Z > 3)].ravel().tolist())

print(Z)

[4, 5, 6, 7, 8, 9, 9]
