In [2]:
# Шаг 6_5_1

# Numpy-100 (задачи 22, 24-30)

# Урок создан на основании известного сборника задач Numpy-100 - https://github.com/rougier/numpy-100

# Постарайтесь не подглядывать в ответы. =)



In [12]:
# Шаг 6_5_2

# 22 Нормализация

# Используйте формулу x_new = (x - μ) / σ,
# где:
#   - x — старое значение
#   - x_new — новое значение
#   - μ — среднее значение (по всей матрице)
#   - σ — стандартное отклонение (по всей матрице)

# для того чтобы "нормализовать" матрицу.

# Мы пока не будем углубляться в математическую суть этой операции, важно лишь, что оба значения для матрицы могут быть вычислены стандартными функциями питу и вам не нужно звать на помощь статистику)

# Пример:
#   [[1, 2],
#    [2, 1]]
#   μ = (1+2+2+1)/4 = 1.5
#   σ = √(1/4 * Σ(xi - μ)²) = 0.5

# Переменная Y содержит исходную матрицу.

# В переменную Z сохраните её "нормализованный" вид, округлив каждое значение в матрице до 2 знака после запятой с помощью numpy.around.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

import numpy as np

Y = np.array([[99,11,55],[33,66,99]])
me = np.mean(Y)
std = np.std(Y)
print(me, std)

Z = np.round((Y-me) / std, 2)
print(Z)

60.5 32.227059023952734
[[ 1.19 -1.54 -0.17]
 [-0.85  0.17  1.19]]


In [13]:
import numpy as np

Z = np.round((Y-np.mean(Y)) / np.std(Y), 2)
print(Z)

[[ 1.19 -1.54 -0.17]
 [-0.85  0.17  1.19]]


In [3]:
# Шаг 6_5_3

# 24.1 Скалярное произведение векторов

# Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и сохраните в переменную Z.

# A и B могут содержать как int, так и float.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать Z.

import numpy as np

A = np.array([1, 3, 5, 7, 9])
B = np.array([-2, 4, -6, 8, -10])

Z = np.dot(A,B)
# Z = A.dot(B)
print(Z)

    # Дока: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html

-54


In [5]:
# Шаг 6_5_4

# 24.2 Умножение матриц

# Даны 2 матрицы: A и B.

# Найдите произведение матриц и сохраните его в переменную Z.

# Если найти произведение матриц невозможно, то запишите в Z строку:
#   "Упс! Что-то пошло не так..."

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать Z.

# Про try-except: https://pythonworld.ru/tipy-dannyx-v-python/isklyucheniya-v-python-konstrukciya-try-except-dlya-obrabotki-isklyuchenij.html

import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [11.5, 12.5, 13.5]
])

try:
    Z = np.dot(A,B)
except:
    Z = 'Упс! Что-то пошло не так...'

print(Z)

Упс! Что-то пошло не так...


In [ ]:
# В комментах есть такое решение:
Z = A.dot(B) if A.shape[1] == B.shape[0] else 'Упс! Что-то пошло не так...'

In [ ]:
# Или такое:
import numpy as np
try:
    Z = A @ B
except ValueError:
    Z = 'Упс! Что-то пошло не так...'



In [19]:
# Шаг 6_5_5

# 25

# Поменяйте знак всех чисел из интервала (3; 9), хранящихся в векторе Z.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только заменить некоторые элементы Z.

Z = np.array([-10, -5, 0, 5, 10])

Z = np.where((Z > 3) & (Z < 9), -Z, Z)
print(Z)


[-10  -5   0  -5  10]


In [ ]:
# Шаг 6_5_6

# 26

# Что выведет на печать код:

print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

'''
У numpy.sum другая сигнатура:
numpy.sum(a, axis=None, dtype=None, ...) — первый аргумент — массив, второй — ось (или axis).
Вызов numpy.sum(range(5), -1) интерпретируется как:
a = range(5) — будет приведено к массиву [0,1,2,3,4]
axis = -1 — сумма по последней оси (для 1D-массива — это всё равно сумма всех элементов)
Использование from numpy import * считается плохой практикой, потому что оно "засоряет" глобальное пространство имён и может привести к таким неочевидным ошибкам или изменениям поведения. Лучше использовать import numpy as np.
'''

# 9
# 10



In [23]:
# Шаг 6_5_7

# 27

# Предположим, Z — целочисленный вектор, например:
#   Z = np.array([1, 2, 3, 4, 5, 6, 7])

# Какие из операций возможны (не приведут к ошибке)?

# Выберите все подходящие ответы из списка.

import numpy as np

Z = np.array([1, 2, 3, 4, 5, 6, 7])

In [24]:
1j*Z

array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j])

In [25]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [26]:
Z < -Z

array([False, False, False, False, False, False, False])

In [27]:
Z/1/1

array([1., 2., 3., 4., 5., 6., 7.])

In [28]:
Z**Z

array([     1,      4,     27,    256,   3125,  46656, 823543])

In [29]:
2 << Z >> 2

array([ 1,  2,  4,  8, 16, 32, 64])

In [30]:
# Шаг 6_5_8

# 28

# Сопоставьте выражения и результат их выполнения.

# Отметьте верные ячейки.

import numpy as np

np.array(0) / np.array(0)

C:\Users\user\AppData\Local\Temp\ipykernel_7300\2695109732.py:11: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [31]:
np.array(0) // np.array(0)

C:\Users\user\AppData\Local\Temp\ipykernel_7300\474058805.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [33]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\user\AppData\Local\Temp\ipykernel_7300\3822400139.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [45]:
# Шаг 6_5_9

A = np.array([-3.1, -5.9, 0, 2.2, 9.8])

Z = np.where((A >= 0), np.ceil(A), np.floor(A))
print(Z)

# Дока 1: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.floor.html?highlight=floor
# Дока 2: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ceil.html

[-4. -6.  0.  3. 10.]


In [105]:
# Шаг 6_5_10

# 30

# Даны 2 вектора целых чисел A и B.

# Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

# Если пересечений нет, то вектор Z будет пустым.

# Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

import numpy as np

A = np.array([0, 9, 7, 1, 3, 7, 5, 2, 5, 1])
B = np.array([3, 1, 3, 7, 4, 1, 8, 1, 1, 8])

Z = np.intersect1d(A,B)
# Z = np.intersect1d(A,B)[::-1] # Если нужна сортировка по убыванию

print(Z)

[1 3 7]
